name: Post coverage comment to pull request

on:
  workflow_run:
    workflows: ["Generate test coverage report"]
    types:
      - completed

jobs:
  test:
    name: Post comment to pull request
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
    
      - name: Post comment
        uses: ewjoachim/python-coverage-comment-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          VERBOSE: true
